CODE_TO_ICON = {

    1000: "images/icons/wi-day-sunny.svg",
    1003: "images/icons/wi-day-cloudy.svg",

    1006: "images/icons/wi-cloud.svg",
    1009: "images/icons/wi-cloud.svg",

    1030: "images/icons/wi-fog.svg",
    1063: "images/icons/wi-day-sprinkle-svg",
    1069: "images/icons/wi-day-sleet.svg",
    1072: "images/icons/wi-rain-mix.svg",
    1087: "images/icons/wi-day-lightning.svg",
    1114: "images/icons/wi-snow-wind/svg",
    1117: "images/icons/wi-snowflake-cold.svg",
    1135: "images/icons/wi-fog.svg",
    1147: "images/icons/wi-snowflake-cold.svg",
    1150: "images/icons/wi-sprinkle.svg",
    1153: "images/icons/wi-sprinkle.svg",
    1168: "images/icons/wi-sleet.svg",
    1171: "images/icons/wi-snowflake-cold.svg",
    1180: "images/icons/wi-sprinkle.svg",
    1183: "images/icons/wi-showers.svg",
    1186: "images/icons/wi-raindrops.svg",
    1189: "images/icons/wi-rain.svg",
    1192: "images/icons/wi-rain.svg",
    1195: "images/icons/wi-rain-wind.svg",
    1198: "images/icons/wi-rain-mix.svg",
    1201: "images/icons/wi-snowflake-cold.svg",
    1204: "images/icons/wi-sleet.svg",
    1207: "images/icons/wi-sleet.svg",
    1210: "images/icons/wi-snow.svg",
    1213: "images/icons/wi-snow.svg",
    1216: "images/icons/wi-snow.svg",
    1219: "images/icons/wi-snow.svg",
    1222: "images/icons/wi-snow.svg",
    1225: "images/icons/wi-snow-wind.svg",
    1237: "images/icons/wi-hail.svg",
    1240: "images/icons/wi-raindrops.svg",
    1243: "images/icons/wi-rain.svg",
    1246:  "images/icons/wi-storm-warning.svg",
    1249: "images/icons/wi-sleet.svg",
    1252: "images/icons/wi-snowflake-cold.svg",
    1255: "images/icons/wi-snow.svg",
    1258: "images/icons/wi-snowflake-cold.svg",
    1261: "images/icons/wi-sleet.svg",
    1264: "images/icons/wi-snowflake-cold.svg",
    1273: "images/icons/wi-storm-showers.svg",
    1276: "images/icons/wi-thunderstorm.svg",
    1279: "images/icons/wi-day-snow-thunderstorm.svg",
    1282: "images/icons/wi-day-snow-thunderstorm.svg"
}